# Main CI/CD configuration file that includes other pipeline files for test and prod environment
# Only triggers for a merge request
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - trigger

triggerjobtest:
  stage: trigger
  trigger:
    include:
      # Files for each pipeline 
      # - local: '/.gitlab-ci-prod.yml'
      - local: '/.gitlab-ci-test.yml'
  rules:
    - if: $CI_COMMIT_BRANCH == 'test'
    # - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  allow_failure: true

triggerjobmain:
  stage: trigger
  trigger:
    include:
      # Files for each pipeline 
      # - local: '/.gitlab-ci-prod.yml'
      - local: '/.gitlab-ci-prod.yml'
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    # - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  allow_failure: true

