# # Main CI/CD configuration file that includes other pipeline files for test and prod environment
# # Only triggers for a merge request
# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# stages:
#   - trigger

# triggerjobtest:
#   stage: trigger
#   trigger:
#     include:
#       # Files for each pipeline 
#       - local: '/.gitlab-ci-prod.yml'
#       - local: '/.gitlab-ci-test.yml'
#   rules:
#     # - if: $CI_COMMIT_BRANCH == 'test'
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#     # - if: $CI_COMMIT_BRANCH == 'test'
#   allow_failure: true

# triggerjobmain:
#   stage: trigger
#   trigger:
#     include:
#       # Files for each pipeline 
#       # - local: '/.gitlab-ci-prod.yml'
#       - local: '/.gitlab-ci-prod.yml'
#   rules:
#     - if: $CI_COMMIT_BRANCH == 'main'
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#   allow_failure: true

# Main CI/CD configuration
stages:
  - trigger

# # Trigger Job to include appropriate pipeline based on branch
# trigger_pipeline:
#   stage: trigger
#   trigger:
#     include:
#       # Include the right pipeline based on the branch
#       - local: '/.gitlab-ci-prod.yml'
#       - local: '/.gitlab-ci-test.yml'
#   rules:
#     # Trigger test pipeline for feature -> test merge requests
#     # - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =="~ /^feature\/.*$/" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'test'
#     # - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =="~ /^feature\/.*$/"
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#     # - if: $CI_COMMIT_BRANCH =~ /^feature\/.*$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'test'
#   allow_failure: true

# triggerjobmain:
#   stage: trigger
#   trigger:
#     include:
#       # Files for each pipeline 
#       # - local: '/.gitlab-ci-prod.yml'
#       - local: '/.gitlab-ci-prod.yml'
#   rules:
#     # - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'test' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#     - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'test'
#     # Trigger prod pipeline for test -> main merge requests
#     # - if: $CI_COMMIT_BRANCH == 'test' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
#   allow_failure: true

trigger_prod_pipeline:
  stage: trigger
  trigger:
    include:
      - local: '/.gitlab-ci-prod.yml'
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
        - '**/*'  # Trigger on any file change
        - '!.gitlab-ci.yml'  # Ignore changes to the .gitlab-ci.yml file
  allow_failure: true