# Main CI/CD configuration file that includes other pipeline files for test and prod environment
trigger_job:
  trigger:
    include:
    - local: '/.gitlab-ci-test.yml'
    - local: '/.gitlab-ci-prod.yml'
