# Main CI/CD configuration file that includes other pipeline files for test and prod environment
# one
trigger_job:
  trigger:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == 'test'
      include:
      - local: '/.gitlab-ci-test.yml'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == 'main'
      include:
      - local: '/.gitlab-ci-prod.yml'
