# #Main CI/CD configuration file that includes other pipeline files for test and prod environment
# trigger_job_main:
#   allow_failure: true
#   trigger:
#     include:
#     - local: '/.gitlab-ci-prod.yml'
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#     - if: $CI_COMMIT_BRANCH == 'main'

stages:
  - trigger

# trigger_main_pipeline:
#   stage: trigger
#   trigger:
#     include:
#       - local: '.gitlab-ci-prod.yml'
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
#     # - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# trigger_test_pipeline:
#   stage: trigger
#   trigger:
#     include:
#       - local: '.gitlab-ci-test.yml'
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "test"'

# trigger_job_test:
#   allow_failure: true
#   trigger:
#     include:
#       - local: '/.gitlab-ci-test.yml'
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#     - if: $CI_COMMIT_BRANCH == 'test'

# trigger_job_main:
#   allow_failure: true
#   trigger:
#     include:
#       - local: '/.gitlab-ci-prod.yml'
#       - local: '/.gitlab-ci-test.yml'
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "push"
#       when: never
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

main:
  stage: trigger
  variables:
    PIPELINE_PARENT_ID : $CI_PIPELINE_ID
  trigger:
    include:
      - local: '/.gitlab-ci-prod.yml'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == 'main'
  allow_failure: true

test:
  stage: trigger
  variables:
    PIPELINE_PARENT_ID : $CI_PIPELINE_ID
  trigger:
    include:
      - local: '/.gitlab-ci-test.yml'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == 'test'
  allow_failure: true
