apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-ai-deployment
  namespace: local-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-ai
  template:
    metadata:
      labels:
        app: local-ai
    spec:
      containers:
      - name: local-ai
        image: quay.io/go-skynet/local-ai:latest
        env:
        - name: THREADS
          value: "4"
        - name: CONTEXT_SIZE
          value: "512"
        volumeMounts:
        - mountPath: /models
          name: model-volume
        resources: {}
      volumes:
      - name: model-volume
        hostPath:
          path: /models

