apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-container
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: dum-app-container
          image: registry.gitlab.com/nevii/terraform_eks/app_temoin:v0.1
          ports:
            - containerPort: 5000  # The port your application is listening on
      imagePullSecrets:
        - name: gitlab-cred
