apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: local-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: gp2  # Ensure this matches your AWS EBS storage class