apiVersion: v1
  kind: Service
  metadata:
    name: app-nodeport-service
    namespace: default
  spec:
    type: NodePort
    selector:
      app: demo-app
    ports:
      - protocol: TCP
        port: 80 # The port on which the service will be exposed
        targetPort: 5000 # The port your application is listening on
        nodePort: 31000  # NodePort range is 30000-32767
