apiVersion: v1
kind: Service
metadata:
  name: service-local-ai
  namespace: k8sgpt-operator-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"
spec:
  selector:
    app: local-ai
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP