---
# Create secret for pulling gitlab registry image
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-cred
  namespace: default
data:
  .dockerconfigjson: "{{ gitlab_config.content | b64decode | b64encode }}"
type: kubernetes.io/dockerconfigjson
---
# Deploy the app and service 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-container
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: dum-app-container
          image: registry.gitlab.com/ara1504621/terraform-test/app_temoin:v1.3_db
          ports:
            - containerPort: 5000  # The port your application is listening on
      imagePullSecrets:
        - name: gitlab-cred