apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-monitor
spec:
  selector:
    matchLabels:
      app: demo-app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - default