apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stock-app-app-monitor
  labels:
    app: stock-app
spec:
  selector:
    matchLabels:
      app: stock-app-app
  endpoints:
  - port: http
    path: /metrics
    interval: 10s