prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    kubeStateMetrics:
      enabled: true
  additionalScrapeConfigs:
    enabled: true
  - job_name: 'scrape_stock_app'
    static_configs:
      - targets: ['service-stock-app-metrics:8000']
        labels:
          app: demo-app
grafana:
  enabled: true
  adminPassword: vxAzurev69007xv
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
    tls: []