- name: Hydrate MySQL Database
  hosts: db_servers
  become: yes
  vars:
    db_host: your-db-endpoint.rds.amazonaws.com  # Replace with your RDS endpoint
    db_name: your_database_name                  # Replace with your database name
    db_user: your_db_username                    # Replace with your database username
    db_password: your_db_password                # Replace with your database password
    db_port: 3306                                # Default MySQL port

  tasks:
    - name: Ensure the database exists
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"

    - name: Create a table and insert initial data
      mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        db: "{{ db_name }}"
        query: |
          CREATE TABLE IF NOT EXISTS employees (
            id INT AUTO_INCREMENT PRIMARY KEY,
            first_name VARCHAR(50),
            last_name VARCHAR(50),
            position VARCHAR(100),
            salary DECIMAL(10, 2)
          );
          INSERT INTO employees (first_name, last_name, position, salary)
          VALUES ('John', 'Doe', 'Software Engineer', 75000.00),
                 ('Jane', 'Smith', 'Product Manager', 85000.00);