apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2  # Ensure this matches your AWS EBS storage class